source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YKPushAndBackSegue_Example', :exclusive => true do
  pod "YKPushAndBackSegue", :path => "../"
end

target 'YKPushAndBackSegue_Tests', :exclusive => true do
  pod "YKPushAndBackSegue", :path => "../"

  
end
